version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram_bot_farfosh
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./downloads:/app/downloads
    restart: always
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
